package com.colddelivery.app.ui.feature

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.clickable
import androidx.compose.foundation.background
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.hilt.navigation.compose.hiltViewModel
import com.colddelivery.app.core.backup.BackupManager
import com.colddelivery.app.core.delivery.customersScheduledForToday
import com.colddelivery.app.core.delivery.deliveryDayFor
import com.colddelivery.app.data.local.entity.*
import com.colddelivery.app.ui.auth.AuthViewModel
import com.colddelivery.app.ui.components.*
import com.colddelivery.app.ui.theme.ColdDeliveryColors
import kotlinx.coroutines.launch
import java.time.LocalDate
import java.time.format.DateTimeFormatter

private fun money(v: Long) = "%,d MMK".format(v)
private fun day(v: Long) = LocalDate.ofEpochDay(v).format(DateTimeFormatter.ofPattern("dd MMM yyyy"))

@Composable private fun Field(value: String, change: (String) -> Unit, label: String, type: KeyboardType = KeyboardType.Text, modifier: Modifier = Modifier) {
    OutlinedTextField(value, change, modifier.fillMaxWidth(), label = { Text(label, fontSize = 12.sp) }, keyboardOptions = KeyboardOptions(keyboardType = type), singleLine = true, shape = com.colddelivery.app.ui.theme.ColdDeliveryShapes.Input)
}
@Composable private fun Select(label: String, value: String, menu: @Composable ColumnScope.() -> Unit) {
    var open by remember { mutableStateOf(false) }
    Box { OutlinedButton({ open = true }, Modifier.fillMaxWidth().heightIn(min = 50.dp), shape = com.colddelivery.app.ui.theme.ColdDeliveryShapes.Input) { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text(label, color = ColdDeliveryColors.SecondaryText, fontSize = 11.sp); Text(value, fontSize = 12.sp) } }; DropdownMenu(open, { open = false }) { Column { menu() } } }
}
@Composable private fun Label(text: String) { Text(text, color = DeepRed, fontSize = 15.sp, fontWeight = FontWeight.Bold) }

@Composable private fun SectionHeading(text: String, modifier: Modifier = Modifier) { Text(text, modifier, color = DeepRed, fontSize = 17.sp, fontWeight = FontWeight.Bold, lineHeight = 22.sp) }

@Composable private fun CompactNumberField(value: String, onValueChange: (String) -> Unit, modifier: Modifier = Modifier, suffix: String = "CTN") {
    Surface(modifier, shape = RoundedCornerShape(13.dp), color = ColdDeliveryColors.Cream, border = androidx.compose.foundation.BorderStroke(1.dp, Gold.copy(alpha = .35f))) {
        Row(Modifier.padding(horizontal = 10.dp, vertical = 8.dp), verticalAlignment = Alignment.CenterVertically) {
            BasicTextField(value, { onValueChange(it.filter(Char::isDigit)) }, Modifier.width(55.dp), textStyle = TextStyle(fontSize = 15.sp, fontWeight = FontWeight.Bold, color = ColdDeliveryColors.Charcoal), keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number), singleLine = true)
            Text(suffix, color = ColdDeliveryColors.SecondaryText, fontSize = 9.sp)
        }
    }
}

@Composable private fun PriceField(value: String, onValueChange: (String) -> Unit, modifier: Modifier = Modifier) {
    Surface(modifier, shape = RoundedCornerShape(13.dp), color = ColdDeliveryColors.Cream, border = androidx.compose.foundation.BorderStroke(1.dp, Gold.copy(alpha = .38f))) {
        Row(Modifier.padding(horizontal = 10.dp, vertical = 9.dp), verticalAlignment = Alignment.CenterVertically) {
            BasicTextField(value, { onValueChange(it.filter(Char::isDigit)) }, Modifier.weight(1f), textStyle = TextStyle(fontSize = 15.sp, fontWeight = FontWeight.Bold, color = ColdDeliveryColors.Charcoal), keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number), singleLine = true)
            Text("MMK", color = Gold, fontSize = 10.sp)
        }
    }
}

@Composable fun PriceScreen(vm: FeatureViewModel = hiltViewModel()) {
    val products by vm.products.collectAsState(); val prices by vm.prices().collectAsState(initial = emptyList()); val values = remember { mutableStateMapOf<Long, String>() }; LaunchedEffect(prices) { prices.forEach { values[it.productId] = it.price.toString() } }
    PremiumPage {
        PremiumPageTitle(stringResource(com.colddelivery.app.R.string.todays_price), stringResource(com.colddelivery.app.R.string.todays_price_subtitle))
        ColdDeliveryCard(Modifier.fillMaxWidth()) { Row(Modifier.fillMaxWidth().padding(14.dp), verticalAlignment = Alignment.CenterVertically) { Text("▣", color = Gold, fontSize = 23.sp); Spacer(Modifier.width(10.dp)); Column { Text(day(vm.today), color = ColdDeliveryColors.Charcoal, fontSize = 16.sp, fontWeight = FontWeight.Bold); Text(LocalDate.now().dayOfWeek.name.lowercase().replaceFirstChar { it.uppercase() }, color = DeepRed, fontSize = 11.sp) } } }
        ColdDeliveryCard(Modifier.fillMaxWidth()) { Column(Modifier.padding(13.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) { Text(stringResource(com.colddelivery.app.R.string.todays_price_info_title), color = Gold, fontSize = 13.sp, fontWeight = FontWeight.Bold); Text(stringResource(com.colddelivery.app.R.string.todays_price_info), color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp, lineHeight = 15.sp) } }
        Row(Modifier.fillMaxWidth().padding(horizontal = 8.dp), horizontalArrangement = Arrangement.SpaceBetween) { Text(stringResource(com.colddelivery.app.R.string.product_code), color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp); Text(stringResource(com.colddelivery.app.R.string.product_name), color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp); Text(stringResource(com.colddelivery.app.R.string.price_mmk), color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp) }
        LazyColumn(Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(8.dp)) { items(products, key = { it.id }) { p -> ColdDeliveryCard(Modifier.fillMaxWidth()) { Row(Modifier.fillMaxWidth().padding(11.dp), verticalAlignment = Alignment.CenterVertically) { Column(Modifier.width(62.dp)) { Text(p.productCode, color = Gold, fontSize = 10.sp, fontWeight = FontWeight.Bold) }; Column(Modifier.weight(1f).padding(horizontal = 6.dp)) { Text(p.productName, fontSize = 13.sp, fontWeight = FontWeight.Bold, maxLines = 2); Text(stringResource(com.colddelivery.app.R.string.carton), color = ColdDeliveryColors.SecondaryText, fontSize = 9.sp) }; PriceField(values[p.id] ?: "", { values[p.id] = it }, Modifier.width(128.dp)) } } } }
        PrimaryRedButton(stringResource(com.colddelivery.app.R.string.save_todays_prices), { vm.viewModelScopeLaunch { products.forEach { p -> values[p.id]?.toLongOrNull()?.let { vm.savePrice(p.id, vm.today, it) } } } }, Modifier.fillMaxWidth())
    }
}

@Composable fun NewDeliveryScreen(onSaved: (Long) -> Unit, vm: FeatureViewModel = hiltViewModel()) {
    val customers by vm.customers.collectAsState(); val products by vm.products.collectAsState(); val prices by vm.prices().collectAsState(initial = emptyList()); var error by remember { mutableStateOf<String?>(null) }; val draft = remember { NewDeliveryDraftState() }; val scope = rememberCoroutineScope(); var open by remember { mutableStateOf(false) }; val todayDate = LocalDate.ofEpochDay(vm.today); val todayDeliveryDay = deliveryDayFor(todayDate); val todayCustomers = customersScheduledForToday(customers, todayDate); val isClosedDay = todayDeliveryDay == null; val closedDayMessage = stringResource(com.colddelivery.app.R.string.closed_day); val noCustomersMessage = stringResource(com.colddelivery.app.R.string.no_customers_scheduled_today); val customer = todayCustomers.firstOrNull { it.id == draft.customerId }; val totals = draft.totals(prices.associate { it.productId to it.price })
    Column(Modifier.fillMaxSize().background(Ivory).verticalScroll(rememberScrollState()).padding(horizontal = 17.dp, vertical = 10.dp).padding(bottom = 90.dp), verticalArrangement = Arrangement.spacedBy(9.dp)) {
        PremiumPageTitle(stringResource(com.colddelivery.app.R.string.new_delivery), stringResource(com.colddelivery.app.R.string.new_delivery_subtitle))
        var customerOpen by remember { mutableStateOf(false) }
        Box {
            ColdDeliveryCard(Modifier.fillMaxWidth().clickable(enabled = !isClosedDay && todayCustomers.isNotEmpty()) { customerOpen = true }) { Row(Modifier.fillMaxWidth().padding(13.dp), verticalAlignment = Alignment.CenterVertically) { Surface(Modifier.size(42.dp), shape = RoundedCornerShape(14.dp), color = DeepRed.copy(alpha = .10f)) { Box(contentAlignment = Alignment.Center) { Text("▣", color = DeepRed, fontSize = 22.sp) } }; Spacer(Modifier.width(10.dp)); Column(Modifier.weight(1f)) { Text(customer?.name ?: stringResource(if (isClosedDay) com.colddelivery.app.R.string.closed_day else com.colddelivery.app.R.string.select_customer), fontSize = 15.sp, fontWeight = FontWeight.Bold); Text(customer?.phone ?: stringResource(if (isClosedDay || todayCustomers.isEmpty()) com.colddelivery.app.R.string.no_customers_scheduled_today else com.colddelivery.app.R.string.customer_details_hint), color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp); customer?.let { Text(it.address, color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp, maxLines = 1) } }; StatusChip(false); if (!isClosedDay && todayCustomers.isNotEmpty()) Text("›", color = Gold, fontSize = 21.sp, modifier = Modifier.padding(start = 4.dp)) } }
            DropdownMenu(customerOpen, { customerOpen = false }) { todayCustomers.forEach { c -> DropdownMenuItem(text = { Column { Text(c.name); Text(c.phone, color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp); Text(c.address, color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp, maxLines = 1) } }, onClick = { draft.selectCustomer(c.id); error = null; customerOpen = false }) } }
        }
        ColdDeliveryCard(Modifier.fillMaxWidth()) { Row(Modifier.fillMaxWidth().padding(12.dp), verticalAlignment = Alignment.CenterVertically) { Text("▣", color = Gold, fontSize = 22.sp); Spacer(Modifier.width(9.dp)); Column { Text(stringResource(com.colddelivery.app.R.string.delivery_date), color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp); Text(day(vm.today), color = ColdDeliveryColors.Charcoal, fontSize = 14.sp, fontWeight = FontWeight.Bold) } } }
        SectionHeading(stringResource(com.colddelivery.app.R.string.delivery_items))
        error?.let { Text(it, color = DeepRed, fontSize = 11.sp) }
        if (draft.items.isEmpty()) ColdDeliveryCard(Modifier.fillMaxWidth()) { Column(Modifier.fillMaxWidth().padding(16.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.spacedBy(4.dp)) { Text("▣", color = Gold, fontSize = 24.sp); Text(stringResource(com.colddelivery.app.R.string.no_products_added), color = ColdDeliveryColors.Charcoal, fontSize = 12.sp, fontWeight = FontWeight.SemiBold); Text(stringResource(com.colddelivery.app.R.string.add_products_hint), color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp) } } else LazyColumn(Modifier.fillMaxWidth().heightIn(max = 235.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { items(draft.items, key = { it.productId }) { line -> val p = products.firstOrNull { it.id == line.productId }; val price = prices.firstOrNull { it.productId == line.productId }?.price ?: 0; ColdDeliveryCard { Column(Modifier.padding(11.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text(p?.productName ?: stringResource(com.colddelivery.app.R.string.product), fontWeight = FontWeight.Bold, fontSize = 13.sp, maxLines = 1); Text(p?.productCode ?: "", color = Gold, fontSize = 9.sp) }; Column(Modifier.width(78.dp)) { Text(stringResource(com.colddelivery.app.R.string.today_price), color = ColdDeliveryColors.SecondaryText, fontSize = 8.sp); Text(if (price > 0) money(price) else stringResource(com.colddelivery.app.R.string.price_missing), color = if (price > 0) ColdDeliveryColors.Charcoal else DeepRed, fontSize = 10.sp, fontWeight = FontWeight.Bold, maxLines = 1) }; Column(Modifier.width(88.dp), horizontalAlignment = Alignment.End) { Text(stringResource(com.colddelivery.app.R.string.amount), color = ColdDeliveryColors.SecondaryText, fontSize = 8.sp); Text(money(line.quantity.toLong() * price), color = DeepRed, fontSize = 11.sp, fontWeight = FontWeight.Bold, maxLines = 1) } }; Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) { Text(stringResource(com.colddelivery.app.R.string.qty), color = ColdDeliveryColors.SecondaryText, fontSize = 9.sp); Spacer(Modifier.width(8.dp)); CompactNumberField(line.quantityText, { v -> draft.updateQuantity(line.productId, v); error = null }, suffix = stringResource(com.colddelivery.app.R.string.ctn)); Spacer(Modifier.weight(1f)); IconButton(onClick = { draft.removeProduct(line.productId); error = null }, modifier = Modifier.size(34.dp)) { Text("×", color = DeepRed, fontSize = 21.sp) } } } } } }
        Box(Modifier.fillMaxWidth()) { PremiumOutlinedButton(stringResource(com.colddelivery.app.R.string.add_product), { open = true }, Modifier.fillMaxWidth()); DropdownMenu(open, { open = false }) { products.forEach { p -> DropdownMenuItem(text = { Text("${p.productCode}  ${p.productName}") }, enabled = draft.items.none { it.productId == p.id }, onClick = { draft.addProduct(p.id); error = null; open = false }) } } }
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { MetricCard(stringResource(com.colddelivery.app.R.string.total_qty), "${totals.quantity} ${stringResource(com.colddelivery.app.R.string.ctn)}", Modifier.weight(1f)); MetricCard(stringResource(com.colddelivery.app.R.string.total_amount), money(totals.amount), Modifier.weight(1f)) }
        PrimaryRedButton(stringResource(com.colddelivery.app.R.string.save_delivery), { scope.launch { try { if (isClosedDay) error(closedDayMessage); if (todayCustomers.isEmpty()) error(noCustomersMessage); if (draft.customerId == 0L) error("Select a customer"); if (draft.items.isEmpty()) error("Add at least one product"); onSaved(vm.saveDelivery(draft.customerId, vm.today, draft.saveItems())) } catch (t: Throwable) { error = t.message ?: "Could not save delivery" } } }, Modifier.fillMaxWidth())
    }
}

@Composable fun AddCustomerScreen(onSaved: () -> Unit, vm: FeatureViewModel = hiltViewModel()) {
    var name by rememberSaveable { mutableStateOf("") }; var phone by rememberSaveable { mutableStateOf("") }; var address by rememberSaveable { mutableStateOf("") }; var note by rememberSaveable { mutableStateOf("") }; var selected by rememberSaveable { mutableStateOf(DeliveryDay.MONDAY) }; val scope = rememberCoroutineScope()
    PremiumPage { PremiumPageTitle("Add Customer", "Create a delivery customer"); ColdDeliveryCard { Column(Modifier.padding(11.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Field(name, { name = it }, "Name *"); Field(phone, { phone = it }, "Phone", KeyboardType.Phone); Field(address, { address = it }, "Address"); Select("Delivery day", selected.name) { DeliveryDay.values().forEach { d -> DropdownMenuItem(text = { Text(d.name) }, onClick = { selected = d }) } }; Field(note, { note = it }, "Note") } }; Spacer(Modifier.weight(1f)); PrimaryRedButton("Save Customer", { scope.launch { if (name.isNotBlank()) { vm.addCustomer(CustomerEntity(name = name, phone = phone, address = address, deliveryDay = selected, note = note, createdAt = System.currentTimeMillis())); onSaved() } } }, Modifier.fillMaxWidth()) }
}

@Composable fun CustomerDetailScreen(customerId: Long, onSaved: () -> Unit, vm: FeatureViewModel = hiltViewModel()) {
    val customers by vm.customers.collectAsState(); val current = customers.firstOrNull { it.id == customerId } ?: return; var name by remember(current) { mutableStateOf(current.name) }; var phone by remember(current) { mutableStateOf(current.phone) }; var address by remember(current) { mutableStateOf(current.address) }; var note by remember(current) { mutableStateOf(current.note) }; var selected by remember(current) { mutableStateOf(current.deliveryDay) }; val scope = rememberCoroutineScope()
    PremiumPage { PremiumPageTitle("Customer Detail", "Edit customer information"); ColdDeliveryCard { Column(Modifier.padding(11.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Field(name, { name = it }, "Name"); Field(phone, { phone = it }, "Phone", KeyboardType.Phone); Field(address, { address = it }, "Address"); Select("Delivery day", selected.name) { DeliveryDay.values().forEach { d -> DropdownMenuItem(text = { Text(d.name) }, onClick = { selected = d }) } }; Field(note, { note = it }, "Note") } }; Text("Sort order  " + current.sortOrder, color = Gold, fontSize = 11.sp); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { PremiumOutlinedButton("Move up", { scope.launch { vm.moveCustomer(customerId, -1) } }, Modifier.weight(1f)); PremiumOutlinedButton("Move down", { scope.launch { vm.moveCustomer(customerId, 1) } }, Modifier.weight(1f)) }; Spacer(Modifier.weight(1f)); TextButton({ scope.launch { vm.updateCustomer(current.copy(isActive = false)); onSaved() } }) { Text("Archive customer", color = DeepRed, fontSize = 11.sp) }; PrimaryRedButton("Save Changes", { scope.launch { vm.updateCustomer(current.copy(name = name, phone = phone, address = address, note = note, deliveryDay = selected)); onSaved() } }, Modifier.fillMaxWidth()) }
}

@Composable fun AddProductScreen(onSaved: () -> Unit, vm: FeatureViewModel = hiltViewModel()) {
    var code by rememberSaveable { mutableStateOf("") }; var name by rememberSaveable { mutableStateOf("") }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope()
    PremiumPage { PremiumPageTitle("Add Product", "Add a carton product to stock"); ColdDeliveryCard { Column(Modifier.padding(11.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Field(code, { code = it }, "Product code *"); Field(name, { name = it }, "Product name *"); Text("Unit  •  CARTON", color = Gold, fontSize = 11.sp); error?.let { Text(it, color = DeepRed, fontSize = 11.sp) } } }; Spacer(Modifier.weight(1f)); PrimaryRedButton("Save Product", { scope.launch { try { if (code.isBlank() || name.isBlank()) error("Code and name are required") else { vm.addProduct(ProductEntity(productCode = code, productName = name, createdAt = System.currentTimeMillis())); onSaved() } } catch (t: Throwable) { error = "Product code must be unique" } } }, Modifier.fillMaxWidth()) }
}

@Composable fun StockInScreen(onSaved: () -> Unit, vm: FeatureViewModel = hiltViewModel()) {
    val products by vm.products.collectAsState(); var selected by remember { mutableStateOf<ProductEntity?>(null) }; var qty by rememberSaveable { mutableStateOf("") }; val scope = rememberCoroutineScope()
    PremiumPage { PremiumPageTitle("Stock In", "Add a new FIFO batch"); ColdDeliveryCard { Column(Modifier.padding(11.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Select("Product", selected?.productName ?: "Select product") { products.forEach { p -> DropdownMenuItem(text = { Text(p.productName) }, onClick = { selected = p }) } }; Field(qty, { qty = it.filter(Char::isDigit) }, "Quantity CTN", KeyboardType.Number); Text("Stock-in date  •  " + day(vm.today), color = ColdDeliveryColors.SecondaryText, fontSize = 11.sp) } }; Spacer(Modifier.weight(1f)); PrimaryRedButton("Save Stock In", { scope.launch { if (selected != null && qty.toIntOrNull() ?: 0 > 0) { vm.stockIn(StockBatchEntity(productId = selected!!.id, stockInDate = vm.today, initialQty = qty.toInt(), remainingQty = qty.toInt(), createdAt = System.currentTimeMillis())); onSaved() } } }, Modifier.fillMaxWidth()) }
}

@Composable fun ProductDetailScreen(productId: Long, vm: FeatureViewModel = hiltViewModel()) {
    val products by vm.products.collectAsState(); val product = products.firstOrNull { it.id == productId }; var total by remember { mutableStateOf(0) }; var batches by remember { mutableStateOf(emptyList<StockBatchEntity>()) }; LaunchedEffect(productId) { total = vm.stockTotal(productId); batches = vm.stockBatches(productId) }
    PremiumPage { PremiumPageTitle(product?.productName ?: "Product", product?.productCode ?: ""); ColdDeliveryCard { Row(Modifier.fillMaxWidth().padding(12.dp), horizontalArrangement = Arrangement.SpaceBetween) { Column { Text("Total stock", color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp); Text("$total CTN", color = if (total == 0) DeepRed else DeliveredGreen, fontSize = 22.sp, fontWeight = FontWeight.Bold) }; Text("FIFO • oldest first", color = Gold, fontSize = 11.sp) } }; Text("FIFO batches", color = DeepRed, fontWeight = FontWeight.Bold); LazyColumn(Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(8.dp)) { items(batches, key = { it.id }) { b -> ColdDeliveryCard { Column(Modifier.padding(12.dp)) { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text("Stock in " + day(b.stockInDate), fontWeight = FontWeight.Bold, fontSize = 13.sp); Text(if (b.remainingQty == 0) "CONSUMED" else "ACTIVE", color = if (b.remainingQty == 0) DeepRed else DeliveredGreen, fontSize = 10.sp, fontWeight = FontWeight.Bold) }; Text("Initial  " + b.initialQty + " CTN    Remaining  " + b.remainingQty + " CTN", color = ColdDeliveryColors.SecondaryText, fontSize = 11.sp) } } } } }
}

@Composable fun EditDeliveryScreen(deliveryId: Long, onSaved: () -> Unit, vm: FeatureViewModel = hiltViewModel()) {
    val products by vm.products.collectAsState(); var customerName by remember { mutableStateOf("") }; var lines by remember { mutableStateOf<List<Pair<Long, String>>>(emptyList()) }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope(); LaunchedEffect(deliveryId) { vm.delivery(deliveryId)?.let { d -> customerName = vm.customer(d.customerId)?.name ?: ""; lines = vm.items(deliveryId).map { it.productId to it.qty.toString() } } }
    PremiumPage { PremiumPageTitle("Edit Delivery", "Update this delivery record"); ColdDeliveryCard { Row(Modifier.fillMaxWidth().padding(12.dp), horizontalArrangement = Arrangement.SpaceBetween) { Text(customerName, fontSize = 15.sp, fontWeight = FontWeight.Bold); Text("Delivery #" + deliveryId, color = Gold, fontSize = 11.sp) } }; error?.let { Text(it, color = DeepRed, fontSize = 11.sp) }; LazyColumn(Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(8.dp)) { items(lines, key = { it.first }) { line -> ColdDeliveryCard { Row(Modifier.fillMaxWidth().padding(11.dp), verticalAlignment = Alignment.CenterVertically) { Text(products.firstOrNull { it.id == line.first }?.productName ?: "Product", Modifier.weight(1f), fontSize = 13.sp, fontWeight = FontWeight.Bold); Field(line.second, { v -> lines = lines.map { if (it.first == line.first) line.first to v.filter(Char::isDigit) else it } }, "CTN", KeyboardType.Number, Modifier.width(108.dp)); TextButton({ lines = lines.filterNot { it.first == line.first } }) { Text("Remove", color = DeepRed, fontSize = 10.sp) } } } } }; TextButton({ products.firstOrNull { p -> lines.none { it.first == p.id } }?.let { lines = lines + (it.id to "1") } }) { Text("+ Add Product", color = DeepRed, fontSize = 12.sp) }; PrimaryRedButton("Save Changes", { scope.launch { try { vm.edit(deliveryId, lines.map { it.first to (it.second.toIntOrNull() ?: 0) }); onSaved() } catch (t: Throwable) { error = t.message ?: "Could not edit delivery" } } }, Modifier.fillMaxWidth()) }
}

@Composable fun VoucherScreen(deliveryId: Long, onUndo: () -> Unit, onEdit: () -> Unit = {}, vm: FeatureViewModel = hiltViewModel()) {
    var customer by remember { mutableStateOf<CustomerEntity?>(null) }; var delivery by remember { mutableStateOf<DeliveryEntity?>(null) }; var items by remember { mutableStateOf<List<DeliveryItemEntity>>(emptyList()) }; val products by vm.products.collectAsState(); val scope = rememberCoroutineScope(); LaunchedEffect(deliveryId) { vm.delivery(deliveryId)?.let { delivery = it; customer = vm.customer(it.customerId) }; items = vm.items(deliveryId) }; val totalQty = items.sumOf { it.qty }; val totalAmount = items.sumOf { it.amount }
    PremiumPage {
        PremiumPageTitle(stringResource(com.colddelivery.app.R.string.delivery_voucher), "#" + deliveryId)
        customer?.let { c -> ColdDeliveryCard(Modifier.fillMaxWidth()) { Column(Modifier.padding(13.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text(c.name, fontSize = 16.sp, fontWeight = FontWeight.Bold); Text(c.phone, color = ColdDeliveryColors.SecondaryText, fontSize = 11.sp); Text(c.address, color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp, maxLines = 2) }; StatusChip(delivery?.status == DeliveryStatus.DELIVERED) }; Text(delivery?.let { day(it.deliveryDate) } ?: "", color = Gold, fontSize = 11.sp, fontWeight = FontWeight.Bold) } } }
        SectionHeading(stringResource(com.colddelivery.app.R.string.item_details))
        ColdDeliveryCard(Modifier.fillMaxWidth()) { Row(Modifier.fillMaxWidth().padding(horizontal = 12.dp, vertical = 9.dp), horizontalArrangement = Arrangement.SpaceBetween) { Text(stringResource(com.colddelivery.app.R.string.product), Modifier.weight(1f), color = ColdDeliveryColors.SecondaryText, fontSize = 9.sp); Text(stringResource(com.colddelivery.app.R.string.qty), Modifier.width(42.dp), color = ColdDeliveryColors.SecondaryText, fontSize = 9.sp); Text(stringResource(com.colddelivery.app.R.string.unit_price), Modifier.width(76.dp), color = ColdDeliveryColors.SecondaryText, fontSize = 9.sp); Text(stringResource(com.colddelivery.app.R.string.amount), Modifier.width(76.dp), color = ColdDeliveryColors.SecondaryText, fontSize = 9.sp) } }
        LazyColumn(Modifier.weight(1f), verticalArrangement = Arrangement.spacedBy(7.dp)) { items(items) { item -> ColdDeliveryCard { Row(Modifier.fillMaxWidth().padding(12.dp), verticalAlignment = Alignment.CenterVertically) { Text(products.firstOrNull { it.id == item.productId }?.productName ?: stringResource(com.colddelivery.app.R.string.product), Modifier.weight(1f), fontWeight = FontWeight.Bold, fontSize = 11.sp, maxLines = 2); Text("${item.qty}", Modifier.width(42.dp), fontSize = 11.sp); Text(money(item.unitPrice), Modifier.width(76.dp), fontSize = 10.sp); Text(money(item.amount), Modifier.width(76.dp), color = DeepRed, fontSize = 10.sp, fontWeight = FontWeight.Bold, maxLines = 1) } } } }
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { MetricCard(stringResource(com.colddelivery.app.R.string.total_qty), "$totalQty ${stringResource(com.colddelivery.app.R.string.ctn)}", Modifier.weight(1f)); MetricCard(stringResource(com.colddelivery.app.R.string.total_price), money(totalAmount), Modifier.weight(1f)) }
        ColdDeliveryCard(Modifier.fillMaxWidth()) { Column(Modifier.padding(12.dp)) { Text(stringResource(com.colddelivery.app.R.string.note), color = Gold, fontWeight = FontWeight.Bold, fontSize = 11.sp); Text(customer?.note?.takeIf { it.isNotBlank() } ?: stringResource(com.colddelivery.app.R.string.no_note), color = ColdDeliveryColors.SecondaryText, fontSize = 11.sp) } }
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { PremiumOutlinedButton(stringResource(com.colddelivery.app.R.string.edit), onEdit, Modifier.weight(1f)); PremiumOutlinedButton(stringResource(com.colddelivery.app.R.string.undo), { scope.launch { vm.undo(deliveryId); onUndo() } }, Modifier.weight(1f)) }
    }
}

@Composable private fun MetricCard(label: String, value: String, modifier: Modifier = Modifier) { ColdDeliveryCard(modifier.heightIn(min = 78.dp)) { Column(Modifier.fillMaxWidth().padding(11.dp), verticalArrangement = Arrangement.spacedBy(3.dp)) { Text(label, color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp); Text(value, color = DeepRed, fontSize = 15.sp, fontWeight = FontWeight.Bold, maxLines = 1) } } }

@Composable fun SettingsScreen(onLogin: () -> Unit, onBackup: () -> Unit = {}, vm: FeatureViewModel = hiltViewModel()) {
    val language by vm.language.collectAsState(); val threshold by vm.lowStockThreshold.collectAsState(); val context = LocalContext.current; var input by remember(threshold) { mutableStateOf(threshold.toString()) }
    PremiumPage { PremiumPageTitle("Settings", "Cold Delivery preferences"); ColdDeliveryCard { Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Text("Language", color = DeepRed, fontWeight = FontWeight.Bold); LanguageSegmentedControl(language, { vm.saveLanguage(it); LanguageManager.apply(context, it) }, Modifier.fillMaxWidth()); Text("Choose the language used throughout the app.", color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp) } }; ColdDeliveryCard { Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Text("Stock alerts", color = DeepRed, fontWeight = FontWeight.Bold); Field(input, { input = it.filter(Char::isDigit) }, "Low-stock threshold", KeyboardType.Number); TextButton({ input.toIntOrNull()?.let(vm::saveThreshold) }) { Text("Save threshold", color = DeepRed, fontSize = 11.sp) } } }; ColdDeliveryCard { Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Text("Backup & restore", color = DeepRed, fontWeight = FontWeight.Bold); Text("Keep a local copy of your delivery data.", color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp); PrimaryRedButton("Open Backup & Restore", onBackup, Modifier.fillMaxWidth()) } }; ColdDeliveryCard { Row(Modifier.fillMaxWidth().padding(12.dp), horizontalArrangement = Arrangement.SpaceBetween) { Text("App version", color = ColdDeliveryColors.SecondaryText); Text("1.0", fontWeight = FontWeight.Bold) } }; Spacer(Modifier.weight(1f)); PremiumOutlinedButton("Logout", onLogin, Modifier.fillMaxWidth()) }
}

@Composable fun BackupScreen(onBack: () -> Unit, vm: FeatureViewModel = hiltViewModel()) {
    val context = LocalContext.current; var status by remember { mutableStateOf<String?>(null) }; val create = rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("application/zip")) { uri -> if (uri != null) status = BackupManager(context, vm.databaseForBackup()).create(uri).fold({ "Backup created" }, { it.message ?: "Backup failed" }) }; val restore = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri -> if (uri != null) status = BackupManager(context, vm.databaseForBackup()).restore(uri).fold({ "Restore complete. Restart the app." }, { it.message ?: "Restore failed" }) }
    PremiumPage { PremiumPageTitle("Backup & Restore", "Protect your local delivery records"); ColdDeliveryCard { Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(7.dp)) { Text("Backup status", color = Gold, fontWeight = FontWeight.Bold); Text(status ?: "No backup action in this session", color = ColdDeliveryColors.SecondaryText, fontSize = 11.sp); Text("Local ZIP backup keeps database data portable.", color = ColdDeliveryColors.SecondaryText, fontSize = 10.sp) } }; PrimaryRedButton("Create Local Backup", { create.launch("cold_delivery_backup_" + System.currentTimeMillis() + ".zip") }, Modifier.fillMaxWidth()); PremiumOutlinedButton("Restore Local Backup", { restore.launch(arrayOf("application/zip")) }, Modifier.fillMaxWidth()); Text("Restore replaces local data and may require an app restart.", color = DeepRed, fontSize = 10.sp); Spacer(Modifier.weight(1f)); TextButton(onBack) { Text("Back", color = DeepRed) } }
}

@Composable fun LoginScreen(onLoggedIn: () -> Unit, vm: FeatureViewModel = hiltViewModel()) { var username by rememberSaveable { mutableStateOf("") }; var password by rememberSaveable { mutableStateOf("") }; PremiumPage { PremiumPageTitle("Cold Delivery", "Offline Delivery Management"); Field(username, { username = it }, "Username"); Field(password, { password = it }, "Password"); Spacer(Modifier.weight(1f)); PrimaryRedButton("Login", { if (username.isNotBlank() && password.isNotBlank()) onLoggedIn() }, Modifier.fillMaxWidth()) } }
@Composable fun AuthLoginScreen(onLoggedIn: () -> Unit, vm: AuthViewModel = hiltViewModel()) { var username by rememberSaveable { mutableStateOf("") }; var password by rememberSaveable { mutableStateOf("") }; var remember by rememberSaveable { mutableStateOf(true) }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope(); PremiumPage { PremiumPageTitle("Cold Delivery", "Offline Delivery Management"); Field(username, { username = it }, "Username"); Field(password, { password = it }, "Password"); Row(verticalAlignment = Alignment.CenterVertically) { Checkbox(remember, { remember = it }); Text("Remember Me", fontSize = 12.sp) }; error?.let { Text(it, color = DeepRed) }; Spacer(Modifier.weight(1f)); PrimaryRedButton("Login", { scope.launch { if (vm.login(username, password, remember)) onLoggedIn() else error = vm.message.value } }, Modifier.fillMaxWidth()) } }
private fun FeatureViewModel.viewModelScopeLaunch(block: suspend () -> Unit) { kotlinx.coroutines.CoroutineScope(kotlinx.coroutines.Dispatchers.Main).launch { block() } }
